#!/usr/bin/env python3
from pathlib import Path
import re,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
q=(root/'js/math-operations-quest.js').read_text(encoding='utf-8')
h=(root/'js/math-operations-dragonswood-host.js').read_text(encoding='utf-8')
r=(root/'js/math-operations-rewards.js').read_text(encoding='utf-8')
c=(root/'css/math-operations-quest.css').read_text(encoding='utf-8')
m=(root/'math-operations-quest.html').read_text(encoding='utf-8')
idx=(root/'index.html').read_text(encoding='utf-8') if (root/'index.html').exists() else ''
modules=(root/'v33-integration/js/integration/modules.js').read_text(encoding='utf-8') if (root/'v33-integration/js/integration/modules.js').exists() else ''
ck('live back link targets index.html#games','href="index.html#games"' in m)
ck('Math Operations runtime is cache-busted and registered','v=56.27.0' in m and ('math-operations-quest.html?v=56.27.0' in idx or "path:'math-operations-quest.html'" in modules))
ck('Custom worksheet rounds are ineligible for account rewards',"eligibleForRewards:diff.rewardEligible&&!state.roundHadCustom&&state.mode==='random'" in q)
ck('Custom practice has explicit no-XP/Gold copy','Worksheet mode does not award Player XP or Gold' in q)
ck('Custom next problem clears instead of reloading same numbers','prepareCustomEntry()' in q and 'const p={operation:state.problem.operation,a:state.problem.a,b:state.problem.b};loadProblem(p,true)' not in q)
ck('Custom mode no longer auto-loads a canned problem','Enter your first worksheet problem above to begin.' in q)
ck('Normal/Hard reject degenerate worksheet problems',"state.difficulty!=='easy'" in q and 'That problem is too simple for Normal or Hard' in q)
ck('Custom coached task count capped','built.tasks.length>18' in q)
ck('Random division includes remainders in later rounds','remainderChance=state.round===1?0:state.round===2?.35:.60' in q)
ck('Active step announced to assistive tech',"setAttribute('aria-current','step')" in q)
ck('Next action receives focus after problem completion','setTimeout(()=>els.newBtn.focus(),0)' in q)
ck('Mixed/random selection is remembered across Custom mode','preCustomOperation' in q)
ck('Round setup is locked after work starts','state.roundSolved>0||state.taskIndex>=0' in q)
ck('Mobile place-value labels remain visible','.place-labels{display:grid}' in c and '.place-labels{display:none}' not in c)
ck('Saved result uses actual problem count','problemsSolved: Number(result.solved || 0)' in h)
ck('Saved result includes roundSolved','roundSolved: Number(result.roundSolved || 0)' in h)
ck('Reward claim uses stable run/round claim ID','runId}_r${Math.max(1,Math.min(3,Number(result.round||1)))' in h)
ck('Reward host checks prior claim before writing','priorClaim.exists()' in h)
ck('Run ID persists across page refreshes','dragonswoodMathQuestRunV1' in q and 'localStorage.getItem(RUN_ID_KEY)' in q)
ck('Custom reward client copy is explicit',"detail.practiceMode === 'custom'" in r)
ck('Easy remains 0 Quest Points',"easy:{label:'Easy',multiplier:0,rewardEligible:false}" in q)
ck('Hard remains 2x Quest Points',"hard:{label:'Hard',multiplier:2,rewardEligible:true}" in q)
ck('Hard does not gain extra account XP','Hard doubles Quest Points, not Player XP.' in q)
ck('Normal walkthrough remains non-answer coaching','renderNormalWalkthrough(task)' in q)
ck('Easy visual coaching remains','renderEasyHint(task)' in q)
ck('Borrow strike styling remains','borrow-original-changed::after' in c)
ck('Reduced-motion support remains','prefers-reduced-motion:reduce' in c)
ck('No !important in Math Operations CSS','!important' not in c)
ck('Grayson Math Operations reference bumped to 57.1','dragonswood-grayson-mode.js?v=57.1' in m)
for name,ok in checks: print(('PASS: ' if ok else 'FAIL: ')+name)
fails=[n for n,o in checks if not o]
print(f'\nRESULT: {len(checks)-len(fails)}/{len(checks)} hardening gates passed')
if fails: sys.exit(1)
