import { WITCHES_META } from "./books/witches/meta.js?v=5";
import { BRIDGE_META } from "./books/bridge-to-terabithia/meta.js?v=1";
import { HOLES_META } from "./books/holes/meta.js?v=1";
import { PERCY1_META } from "./books/percy-jackson-1/meta.js?v=1";
import { PERCY2_META } from "./books/percy-jackson-2/meta.js?v=1";
import { PERCY3_META } from "./books/percy-jackson-3/meta.js?v=1";
import { PERCY4_META } from "./books/percy-jackson-4/meta.js?v=1";
import { PERCY5_META } from "./books/percy-jackson-5/meta.js?v=1";
import { KEEPER1_META } from "./books/keeper-1/meta.js?v=1";
import { KEEPER2_META } from "./books/keeper-2/meta.js?v=1";
import { KEEPER3_META } from "./books/keeper-3/meta.js?v=1";
import { KEEPER4_META } from "./books/keeper-4/meta.js?v=1";
import { HARRY_POTTER_META } from "./books/harry-potter/meta.js?v=1";
import { WONDER_META } from "./books/wonder/meta.js?v=1";
import { WILD_ROBOT_1_META } from "./books/wild-robot-1/meta.js?v=1";

export const BOOKS = [
  {
    id: "witches",
    title: "The Witches",
    author: "Roald Dahl",
    category: "Class Read",
    teaser: "A boy discovers that real witches do not wear pointed hats or look easy to spot. They hide in ordinary places, and they have a frightening plan for children. This is a sharp, fast story about noticing clues, staying brave, and thinking your way out of serious trouble.",
    pages: WITCHES_META.pages,
    cover: "class-library/covers/classroom/witches-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/witches/book.json?v=5",
    previousPages: 88,
    progressMigrations: { "witches-reflow-1": 151, "witches-reflow-2": 151, "witches-reflow-3": 458, "witches-reflow-4": 257, "witches-reflow-5": 188 },
    progressVersion: "witches-reflow-6",
    badge: "New flowing reader"
  },
  {
    id: "harry-potter-1",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    category: "Fantasy",
    teaser: "Harry has spent his life being treated like he does not belong. Then a letter reveals a hidden world of magic, a school full of secrets, and a past nobody explained to him. Pick this if you like mysteries, loyal friends, strange creatures, and discovering that an ordinary-looking kid may be anything but ordinary.",
    pages: HARRY_POTTER_META.pages,
    cover: "class-library/covers/classroom/harry-potter-classroom.jpg",
    kind: "images",
    imagePattern: "class-library/books/harry-potter/pages/page-{page}.jpg",
    textFile: "class-library/books/harry-potter/text/pages.json",
    textLayoutFile: "class-library/books/harry-potter/text/layout.json"
  },
  {
    id: "percy-jackson-1",
    title: "The Lightning Thief",
    series: "Percy Jackson · Book 1",
    seriesId: "percy-jackson",
    seriesNumber: 1,
    author: "Rick Riordan",
    category: "Fantasy",
    teaser: "Percy is used to school trouble, but not teachers turning into monsters or myths stepping into real life. A dangerous quest forces him to figure out who he is and whom he can trust. It moves quickly, stays funny without becoming silly, and gives every chapter a new problem to solve.",
    pages: PERCY1_META.pages,
    cover: "class-library/covers/classroom/percy-jackson-1-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/percy-jackson-1/book.json?v=1",
    previousPages: 231,
    progressVersion: "percy1-reflow-1",
    badge: "Percy Jackson · 1 · Illustrated"
  },
  {
    id: "percy-jackson-2",
    title: "The Sea of Monsters",
    series: "Percy Jackson · Book 2",
    seriesId: "percy-jackson",
    seriesNumber: 2,
    author: "Rick Riordan",
    category: "Fantasy",
    teaser: "Percy's safest place is in danger, and the only possible rescue lies across a sea where monsters are very real. The mission brings strange allies, risky choices, and questions about what makes someone a true friend. Start here only after The Lightning Thief.",
    pages: PERCY2_META.pages,
    cover: "class-library/covers/classroom/percy-jackson-2-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/percy-jackson-2/book.json?v=1",
    previousPages: 174,
    progressVersion: "percy2-reflow-1",
    badge: "Percy Jackson · 2 · Illustrated"
  },
  {
    id: "percy-jackson-3",
    title: "The Titan's Curse",
    series: "Percy Jackson · Book 3",
    seriesId: "percy-jackson",
    seriesNumber: 3,
    author: "Rick Riordan",
    category: "Fantasy",
    teaser: "A rescue mission turns into a race involving missing friends, powerful enemies, and a prophecy nobody fully understands. Percy has to decide when to follow orders and when to trust his own judgment. Start here after The Sea of Monsters.",
    pages: PERCY3_META.pages,
    cover: "class-library/covers/classroom/percy-jackson-3-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/percy-jackson-3/book.json?v=1",
    previousPages: 194,
    progressVersion: "percy3-reflow-1",
    badge: "Percy Jackson · 3 · Illustrated"
  },
  {
    id: "percy-jackson-4",
    title: "The Battle of the Labyrinth",
    series: "Percy Jackson · Book 4",
    seriesId: "percy-jackson",
    seriesNumber: 4,
    author: "Rick Riordan",
    category: "Fantasy",
    teaser: "An underground maze is spreading beneath the world, and every path inside it can change. Percy and his friends must navigate traps, enemies, and choices that are harder than any map can solve. Start here after The Titan's Curse.",
    pages: PERCY4_META.pages,
    cover: "class-library/covers/classroom/percy-jackson-4-classroom.jpg",
    file: "class-library/books/percy-jackson-4-battle-of-the-labyrinth.pdf",
    badge: "Percy Jackson · 4"
  },
  {
    id: "percy-jackson-5",
    title: "The Last Olympian",
    series: "Percy Jackson · Book 5",
    seriesId: "percy-jackson",
    seriesNumber: 5,
    author: "Rick Riordan",
    category: "Fantasy",
    teaser: "The conflict Percy has been preparing for finally reaches New York. The battles are larger, but the hardest choices are about loyalty, sacrifice, and what kind of hero Percy wants to be. Start here after The Battle of the Labyrinth.",
    pages: PERCY5_META.pages,
    cover: "class-library/covers/classroom/percy-jackson-5-classroom.jpg",
    file: "class-library/books/percy-jackson-5-last-olympian.pdf",
    badge: "Percy Jackson · 5"
  },
  {
    id: "keeper-1",
    title: "Keeper of the Lost Cities",
    series: "Keeper of the Lost Cities · Book 1",
    seriesId: "keeper-lost-cities",
    seriesNumber: 1,
    author: "Shannon Messenger",
    category: "Fantasy",
    teaser: "Sophie has always known things she should not be able to know. When she learns why, she enters a hidden world that seems perfect until its secrets begin to surface. Choose this if you like powerful abilities, complicated friendships, and mysteries that keep getting bigger.",
    pages: KEEPER1_META.pages,
    cover: "class-library/covers/classroom/keeper-1-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/keeper-1/book.json?v=1",
    progressVersion: "keeper1-reflow-1",
    badge: "Keeper · 1 · Illustrated"
  },
  {
    id: "keeper-2",
    title: "Exile",
    series: "Keeper of the Lost Cities · Book 2",
    seriesId: "keeper-lost-cities",
    seriesNumber: 2,
    author: "Shannon Messenger",
    category: "Fantasy",
    teaser: "Sophie is still learning where she belongs when a rare and dangerous creature needs her help. The rescue pulls her toward new secrets and makes it harder to know which rules should be trusted. Start here after Keeper of the Lost Cities.",
    pages: KEEPER2_META.pages,
    cover: "class-library/covers/classroom/keeper-2-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/keeper-2/book.json?v=1",
    progressVersion: "keeper2-reflow-1",
    badge: "Keeper · 2 · Illustrated"
  },
  {
    id: "keeper-3",
    title: "Everblaze",
    series: "Keeper of the Lost Cities · Book 3",
    seriesId: "keeper-lost-cities",
    seriesNumber: 3,
    author: "Shannon Messenger",
    category: "Fantasy",
    teaser: "A dangerous fire and a growing mystery force Sophie to test the limits of her abilities. Her choices affect her friends, her family, and a world that is becoming less safe. Start here after Exile.",
    pages: KEEPER3_META.pages,
    cover: "class-library/covers/classroom/keeper-3-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/keeper-3/book.json?v=1",
    progressVersion: "keeper3-reflow-1",
    badge: "Keeper · 3 · Illustrated"
  },
  {
    id: "keeper-4",
    title: "Neverseen",
    series: "Keeper of the Lost Cities · Book 4",
    seriesId: "keeper-lost-cities",
    seriesNumber: 4,
    author: "Shannon Messenger",
    category: "Fantasy",
    teaser: "Sophie and her friends leave familiar safety behind to search for answers themselves. The group has to work out whom to trust while every discovery raises a new question. Start here after Everblaze.",
    pages: KEEPER4_META.pages,
    cover: "class-library/covers/classroom/keeper-4-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/keeper-4/book.json?v=1",
    progressVersion: "keeper4-reflow-1",
    badge: "Keeper · 4 · Illustrated"
  },
  {
    id: "wonder",
    title: "Wonder",
    author: "R. J. Palacio",
    category: "Realistic",
    teaser: "Auggie is starting school after years of learning at home, and he knows people will notice his face before they know him. The story follows several students as first impressions turn into friendship, mistakes, and difficult choices. It is honest about fitting in without pretending kindness is always easy.",
    pages: WONDER_META.pages,
    cover: "class-library/covers/classroom/wonder-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/wonder/book.json?v=1",
    previousPages: 220,
    progressVersion: "wonder-reflow-1",
    badge: "123 chapters · Reflow"
  },
  {
    id: "bridge-to-terabithia",
    title: "Bridge to Terabithia",
    author: "Katherine Paterson",
    category: "Realistic",
    teaser: "Jess expects the new girl to be a rival, but Leslie becomes the friend who sees more in him than anyone else does. Together they create Terabithia, a kingdom where courage and imagination feel real. This starts as a friendship adventure and grows into a story that stays with you.",
    pages: BRIDGE_META.pages,
    cover: "class-library/covers/classroom/bridge-to-terabithia-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/bridge-to-terabithia/book.json?v=1",
    previousPages: 74,
    progressVersion: "bridge-reflow-1",
    badge: "Illustrated flowing reader"
  },
  {
    id: "holes",
    title: "Holes",
    author: "Louis Sachar",
    category: "Adventure",
    teaser: "Stanley is sent to Camp Green Lake, where there is no lake and every boy must dig one enormous hole each day. The adults claim it builds character, but Stanley begins to suspect they are searching for something. The story connects clues from different times until the strange pieces finally fit.",
    pages: HOLES_META.pages,
    cover: "class-library/covers/classroom/holes-classroom.jpg",
    kind: "reflow",
    contentFile: "class-library/books/holes/book.json?v=1",
    progressVersion: "holes-reflow-1",
    badge: "Illustrated flowing reader"
  },
  {
    id: "matilda",
    title: "Matilda",
    author: "Roald Dahl",
    category: "Funny",
    teaser: "Matilda loves books, notices everything, and is far smarter than the adults who keep underestimating her. School brings one wonderful teacher, one terrifying headmistress, and a surprising ability Matilda did not know she had. Read this for clever payback, dark humor, and a hero who refuses to stay powerless.",
    pages: 233,
    cover: "class-library/covers/classroom/matilda-classroom.jpg",
    file: "class-library/books/matilda.pdf",
    textFile: "class-library/books/matilda/text/pages.json",
    textLayoutFile: "class-library/books/matilda/text/layout.json"
  },
  {
    id: "charlie",
    title: "Charlie and the Chocolate Factory",
    author: "Roald Dahl",
    category: "Funny",
    teaser: "Charlie has very little except a loving family and a view of the most mysterious chocolate factory in the world. One golden ticket gives him the chance to step inside, where every room is stranger than the last. The fun comes from the inventions, but the choices each visitor makes matter just as much.",
    pages: 89,
    cover: "class-library/covers/classroom/charlie-classroom.jpg",
    file: "class-library/books/charlie-and-the-chocolate-factory.pdf"
  },
  {
    id: "wild-robot-1",
    title: "The Wild Robot",
    series: "The Wild Robot · Book 1",
    seriesId: "wild-robot",
    seriesNumber: 1,
    author: "Peter Brown",
    category: "Adventure",
    teaser: "Roz wakes on a wild island with no instructions for surviving there. To live among the animals, she has to observe, adapt, and learn what it means to care for someone else. The chapters are short, but the questions about nature, family, and belonging are much bigger.",
    pages: WILD_ROBOT_1_META.pages,
    cover: "class-library/covers/classroom/wild-robot-1-classroom.jpg",
    file: "class-library/books/wild-robot-1.pdf",
    badge: "Wild Robot · 1"
  },
  {
    id: "wild-robot-2",
    title: "The Wild Robot Escapes",
    series: "The Wild Robot · Book 2",
    seriesId: "wild-robot",
    seriesNumber: 2,
    author: "Peter Brown",
    category: "Adventure",
    teaser: "Roz has been taken away from the island and placed on a farm where people expect her to behave like an ordinary machine. She must understand her new home while quietly searching for a way back to the family she chose. Start here after The Wild Robot.",
    pages: 253,
    cover: "class-library/covers/classroom/wild-robot-2-classroom.jpg",
    file: "class-library/books/wild-robot-2-escapes.pdf",
    badge: "Wild Robot · 2"
  },
  {
    id: "wild-robot-3",
    title: "The Wild Robot Protects",
    series: "The Wild Robot · Book 3",
    seriesId: "wild-robot",
    seriesNumber: 3,
    author: "Peter Brown",
    category: "Adventure",
    teaser: "A threat spreading through the ocean reaches Roz's island and puts many kinds of animals in danger. Solving it will require travel, cooperation, and choices no single creature can make alone. Start here after The Wild Robot Escapes.",
    pages: 236,
    cover: "class-library/covers/classroom/wild-robot-3-classroom.jpg",
    file: "class-library/books/wild-robot-3-protects.pdf",
    badge: "Wild Robot · 3"
  }
];
